name: gatsby-publish

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Fetch latest report
      run: |
        yarn install --pure-lockfile
        yarn get-report

    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        deploy-branch: master
        gatsby-args: --prefix-paths

